### ISSUE TITLE
[Bug] Some custom model files don't compile

### ISSUE THREAD

**Issue by Cryptizism** [Goldorion/MCreatorFabricGenerator#135]
**Describe the bug**
When trying to build my fabric mod on mcreator with a model I made in blockbench it shows an error when I try save an entity I created.

**Log**
https://pastebin.com/atqHxHvT

**Affected version(s)**

Minecraft Fabric 1.16.5 Release 1.2

**To Reproduce**
1.  Go to workspace and add a living entity
2. Add models and textures
3. Follow through with defaults (Make sure it's a mob)
4. Press Save mod element
5. Error appears 

**Expected behavior**
It should show no error and let you build the mod

**Screenshots**
![image](https://user-images.githubusercontent.com/60571306/128772517-1f124cab-3a61-48cb-8958-4e3c6cd335c5.png)

**Additional context**
I tried with another simpler model and it didn't work, tried exporting in both normal forge and fabric format too. Same thing. The only difference was that the forge one let me set new animations

**Comment by Goldorion** [comment]
Can you provide your model file?

**Comment by Cryptizism** [comment]
Here are the 2 models I tested with
https://drive.google.com/drive/folders/1525ZK4NKGbtUud4d6LNcExWkRerv1Neb?usp=sharing #

**Comment by Goldorion** [comment]
When I implemented custom entities, I supported custom models for Forge because I wasn't aware of the existence of a Fabric exporter plugin in BlockBench. As forge and Fabric use different mapping, the names of methods are also different. So, when you export a model with the Fabric exporter, it will add a method (`setAngles`). With Forge, this method is called `setRotationAngles`. When you import the model in MCreator, you can define animations, and it will add this method with the code for animations. Then, inside my Fabric generator, I can simply replace the method name and a few parameters in order to use Fabric's names. However, when you export your model directly as a Fabric model, it causes a problem because the method MCreator adds (and then, I replace it with FreeMarker) is already inside the model. In order to fix this problem, I would need to change a bit how MCreator handles this. So, currently, if you want to use a custom model, you need to make it a Forge model (Forge 1.15-1.16 (MCP)).
