### ISSUE TITLE
[Request] Trinkets 

### ISSUE THREAD

**Issue by ghost** [Goldorion/MCreatorFabricGenerator#137]
**Feature**
Add ability to interact with [Trinkets API](https://github.com/emilyploszaj/trinkets/wiki/Trinkets-API)

**Describe why you want the feature**
Add items like curious (artefacts, rings etc)

Thanks,
Regards,
Szu.

Btw.
Really great work Man!

**Comment by ghost** [comment]
+ Can you also add a note to the release, what version fabric api version support?

**Comment by Goldorion** [comment]
External APIs will need to be added as external plugins. I don't want to add support for extra features when I still don't have a complete generator.

> Can you also add a note to the release, what version fabric api version support?

You can see the current Fabric API version when you select the generator on the generator selector window. Otherwise, I always write the new Fabric API version when I update it. The current version is 0.37.1.

**Comment by ghost** [comment]
Thanks for answer :)

**Comment by vico93** [comment]
Any updates about this?
