### ISSUE TITLE
[Request] Github Actions Autobuild Releases

### ISSUE THREAD

**Issue by Merith-TK** [Goldorion/MCreatorFabricGenerator#171]
AS the title suggests, have github actions automatically build releases for each branch on commit,

**Comment by Goldorion** [comment]
I don't want to have a new release each time I push a commit. Sometimes, I need several commits for something or I want to make an update with several things. In addition, I still need to manually update the plugin page on the MCreator's website.

**Comment by Merith-TK** [comment]
No no, It wont make an actual release on the release page, it will just make a compiled release availiable through github actions, alot of repos do this for their "Dev Builds"

**Comment by Merith-TK** [comment]
I will say, you can take a look at CC:T/R's github-actions config in our [main-ci.yml](https://github.com/cc-tweaked/cc-restitched/blob/1.17.1/.github/workflows/main-ci.yml) file, has some gradle things and how to output build artifacts so there is that.

**Comment by Micasddsa** [comment]
Wanted to add something here. You can just download the source code and zip the contents of the "src" folder to get a dev build. works just as intended. Auto-building is kinda useless because of how easy it is to do. I will admit that it isn't obvious how to do this at first unless you know the folder structure of a MCreator Plugin so maybe i'll make a PR editing the "Read Me" to contain instructions on how to do it.
