### ISSUE TITLE
How to create a workspace with Fabric 1.17.1

### ISSUE THREAD

**Issue by thomasglasser** [Goldorion/MCreatorFabricGenerator#182]
## Edit from Goldorion:
```I made several tests and sadly, due to how MCreator creates workspaces, I can't solve the problem. However, you can still fix the problem yourself by following these steps:
1. Open your workspace folder
2. Create the following folders `src/main/resources/`
3. Download and place this file inside the `resources` folder. [modid.accesswidener.txt](https://github.com/Goldorion/Fabric-Generator-MCreator/files/8274579/modid.accesswidener.txt)
4. Rename the file so it follows this template `yourModID.accesswidener`. Replace `yourModID` with the ID of your mod.
5. Go back inside MCreator and re-run the setup. If you did everything correctly, your workspace should be created correctly.

I'm sorry to have to make you this, but this is the only you can create a workspace for the moment. I will try to see if I can switch from Access wideners to Mixins as I'm only using it for fishing rods currently.
```

----------------------------------------------

## Original issue
When attempting to open a new Workspace, it doesn't open.

(https://www.toptal.com/developers/hastebin/axopodanaj.yaml)

MCreator 2021.3.54000, Generator beta 1.6, Windows 11

1. Go to MCreator Open Page
2. Click on New Workspace
3. Click on Fabric mod
4. Click on 1.17.1
5. Fill in other info
6. Click on Create new workspace
7. See error

Expected to be created normally with no errors.

![image](https://user-images.githubusercontent.com/63979449/158028358-aad13c98-4122-4276-a8fb-4bb38a4c9aef.png)

**Comment by thomasglasser** [comment]
In case you want it:
[testfab.zip](https://github.com/Goldorion/Fabric-Generator-MCreator/files/8238042/testfab.zip)

**Comment by thomasglasser** [comment]
Oh, and generator in the .mcreator file is already 1.17.1

**Comment by TestSubjectLizzy** [comment]
I am also getting this bug 

Executing Gradle task: tasks
Build info: MCreator 2021.3.53117, fabric-1.17.1, 64-bit, 16337 MB, Windows 10, JVM 16.0.2, JAVA_HOME: C:\Users\ME\Desktop\MCreator20213\jdk
 
> Configure project :
Fabric Loom: 0.10.66
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'hcm'.
> Failed to provide loom:mappings:layered+hash.2192 : java.lang.RuntimeException: Could not find access widener file @ C:\Users\ME\MCreatorWorkspaces\hcm\src\main\resources\hcm.accesswidener
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 8s
 
BUILD FAILED
Task completed in 9 seconds

**Comment by Goldorion** [comment]
I made several tests and sadly, due to how MCreator creates workspaces, I can't solve the problem. However, you can still fix the problem yourself by following these steps:

1. Open your workspace folder
2. Create the following folders `src/main/resources/`
3. Download and place this file inside the `resources` folder. [modid.accesswidener.txt](https://github.com/Goldorion/Fabric-Generator-MCreator/files/8274579/modid.accesswidener.txt)
4. Rename the file so it follows this template `yourModID.accesswidener`. Replace `yourModID` with the ID of your mod.
5. Go back inside MCreator and re-run the setup. If you did everything correctly, your workspace should be created correctly.

I'm sorry to have to make you this, but this is the only you can create a workspace for the moment. I will try to see if I can switch from Access wideners to Mixins as I'm only using it for fishing rods currently.

**Comment by ImNotThinkQuack** [comment]
Hi, I have been pulling my hair out with any possible reason as to why this is not working, I have followed all 5 steps closely and have triple checked them all to make sure I made no mistake and I am quite confident that I have not. I just wanted to make a new biome spawn in the end :( . No matter what I do the error for failed workspace always tells me that I do not have an accesswidener file in C;\Users\[my name]\MCreatorWorkspaces\endbiomes\src\main\resources\endbiomes.accesswidener... What am I doing wrong???

I have attached 2 images of what the log of the workspace setup failure looks like as well as my resources folder's contents.
![image](https://user-images.githubusercontent.com/101850708/158927318-98bd39dc-887a-4bd6-996d-1efe459962a7.png)
![image](https://user-images.githubusercontent.com/101850708/158927399-3128356f-b67d-4f86-b90f-b6b9178fd653.png)

**please help me**

**Comment by Goldorion** [comment]
When the file is saved, re-run the setup with the button. If it doesn't work, make sure you did exactly how explained because I can assure you it works.

**Comment by ImNotThinkQuack** [comment]
https://user-images.githubusercontent.com/101850708/159026587-c630feb3-8aaf-4608-abfc-19b1d76649f1.mp4

**Yeah, please tell me what I'm doing wrong...?**

**Comment by Goldorion** [comment]
The icon of the file seems to show this is still a TXT file. You need to remove the `.txt`.

**Comment by ImNotThinkQuack** [comment]
What file extension do I change it to? Just a normal file?

**Comment by ImNotThinkQuack** [comment]
It's working!!!
Thank you!

**Comment by minecraftmaker12** [comment]
i removed the .txt at the end of the file's name. it still shows the error.

**Comment by eTrane99** [comment]
Yeah I'm still having this issue even with the troubleshooting steps. Before you say "Follow the steps, I assure you it works:"
- File extension is correct and shows as ACCESSWIDENER
- Location is correct and triple checked
- MCreator is fully updated and restarted multiple times
- I am running the latest Java Runtime Environment
The current solution is hardly the end-all in its current state. I understand this is probably a small time project, but even adding a script before runtime that adds this folder to the directory would be a better solution than having users run it manually.

**Comment by Goldorion** [comment]
>       The current solution is hardly the end-all in its current state. I understand this is probably a small time project, but even adding a script before runtime that adds this folder to the directory would be a better solution than having users run it manually.

I'm totally aware of this. I will try to check to replace the access widener file by a mixin in the future. However, it can also cause more problem and potentially make mods incompatible. Concerning a script to add it directly, generators do not support something for this at this step of the creation of a workspace. I can try some tricky ways, but also I am not sure it will work or make mods compatible between them. It needs more research, but I wanted to release the 1.17.1 before taking a lot of time into this problem.

For the moment, all I can tell you is to try again and be careful with every step because I tested, re-tested and re-re-tested and it always worked.

**Comment by minecraftmaker12** [comment]
nvm i had to make it 1.16.5 and then convert it. no need for the file
