### ISSUE TITLE
[BUG] Procedures giving build errors in the main mod file

### ISSUE THREAD

**Issue by ghost** [Goldorion/MCreatorFabricGenerator#45]
**Describe the bug**
MCreator gives a build error in the main mod file when a procedure is created.

**Log**
https://controlc.com/99209fdf

**Affected version(s):** 1.0.0 Alpha 2

**To Reproduce**
1. Create a procedure
2. Save the procedure
3. MCreator gives a build error

**Expected behavior**
Build without giving a error.

**Screenshots**
Not applicable.

**Additional context**
No additional context.

**Comment by CrispyChips6660** [comment]
does this happen for any procedure?
Can you attach your procedure as a file and briefly explain what it does? @NOYBss

**Comment by ghost** [comment]
I first created a play_sound procedure but when I used it, MCreator gave this error, (I thought it was a problem with the procedure I added) then I tried it with a existing procedure that the Fabric Generator adds support but I got the same error. I then tested it with some other procedures but they also gave the same error.

**Comment by KlemenDEV** [comment]
This is caused because of the way global triggers are registered. I suggest registering this in a bit different way. I can provide an idea of this if interested (a pull request)?

Basically I would move EVENT.register calls to optional constructor of the procedure and add this only when global trigger is selected and then construct a procedure object from the main mod file.
