### ISSUE TITLE
[BUG] tools & armour don't work at all

### ISSUE THREAD

**Issue by connorhedgehog** [Goldorion/MCreatorFabricGenerator#62]
so basically, when i make a tool (pickaxe, sword, axe, etc) or armour mcreator either says i need to regenerate the code (when i do it comes up again no matter what)

**Log**
i seriously can't find the mcreator.log, will add it when i find it though

**Affected version(s)** 1.0.0-alpha.5

**To Reproduce**
okay so, first, make a workspace with the plugin
then click the plus in workspace
and then make armour or tools
save mod element
boom, can't export no matter what

**Expected behavior**
what i expected to happen, was it to work and let me export and use the mod as, a mod, that works

**Comment by Goldorion** [comment]
For the armors, I know the bug and I can't resolve it before the open-sourcing of MCreator because with Fabric, we have to select a sound when it's equipped, but Forge doesn't require it, so you need to select one. However, if you talk of another bug, we can't resolve it, if you don't give us the console log at least.

**Comment by Goldorion** [comment]
The log file of MCreator ca be found at /Users/yourUser.mcreator/log./. The file named mcreator.log is the latest log file.

**Comment by CrispyChips6660** [comment]
"i seriously can't find the mcreator.log, will add it when i find it though"
The mcreator.log is on <your user directory>/.mcreator/logs. Also you should attach your workspace in this issue.

**Comment by Goldorion** [comment]
I tested the armor and all available tools with the generator, and I had no error in the console. For the armors, be sure to select a sound when the armor is equipped because otherwise, I know, there is a bug. This bug is here because with Fabric we have to define a sound for this setting, but for a Forge mod, it's optional, so MCreator doesn't obligate you to select sound. I can't fix this bug for the moment, except if I define a sound myself when no sound is selected. For the tools, regenerate your code and then, if you still have a compilation error, please open a new ticket with the console log (pastebin or hastebin please) and your workspace. I close this ticket.
